import AppConfig from "@/config/appConfig";

// ============ CORE TEAM DATA ============
const coreTeam = [
  {
    name: "Ayush Kumar",
    designation: "President",
    department: "Student Technical Council - CEP",
    image: AppConfig.imageUrls.president,
    email: "ayush_2412res47@iitp.ac.in",
    linkedin: "https://www.linkedin.com/in/ayush-kumar-601594351",
    description:
      "Leading STC's vision and driving innovation across all wings. Passionate about entrepreneurship and technology.",
  },
  {
    name: "Satyam Kumar",
    designation: "Vice President",
    department: "Student Technical Council - CEP",
    image: AppConfig.imageUrls.vicePresident,
    email: "satyam_24a12res597@iitp.ac.in",
    linkedin: "https://www.linkedin.com/in/satyamkumariitp/",
    description:
      "Overseeing technical initiatives and research projects. Expert in competitive programming and AI.",
  },
  {
    name: "Hariom Kumar",
    designation: "General Secretary",
    department: "Student Technical Council - CEP",
    image: AppConfig.imageUrls.generalSecretary,
    email: "hariom_2312res276@iitp.ac.in",
    linkedin: "https://www.linkedin.com/in/hariom-kumar-29309b2b5/",
    description:
      "Managing operations and career development programs. Focused on bridging academia and industry.",
  },
  {
    name: "Kumar Aayush",
    designation: "Treasurer",
    department: "Student Technical Council - CEP",
    image: AppConfig.imageUrls.treasurer,
    email: "aayush_2312res805@iitp.ac.in",
    linkedin: "https://www.linkedin.com/in/kumaraayush125/",
    description:
      "Managing financial operations and budget planning. Expertise in financial modeling and analysis.",
  },
];

// ============ COUNCIL MEMBERS ============
const councilMembers = [
  {
    name: "Amrit Raj",
    designation: "Council Head",
    department: "Student Technical Council - CEP",
    image: AppConfig.imageUrls.councilHead,
    email: "amrit_2312res105@iitp.ac.in",
    linkedin: "https://www.linkedin.com/in/amrit-raj2104/",
    description:
      "Leading the Student Technical Council to foster innovation, impactful event management and holistic student growth across IIT Patna.",
  },
  {
    name: "Shivam Kumar",
    designation: "Overall Management Lead",
    department: "Student Technical Council - CEP",
    image: AppConfig.imageUrls.overallManagementLead,
    email: "shivam_24a12res637@iitp.ac.in",
    linkedin: "https://www.linkedin.com/in/shivam-kumar-iitp/",
    description:
      "Coordinating overall management and strategic planning. Experienced in project management and leadership.",
  },
  {
    name: "Badal Raj",
    designation: "Tatva Cell Head",
    department: "Student Technical Council - CEP",
    image: AppConfig.imageUrls.tatvaCellHead,
    email: "badal_2312res218@iitp.ac.in",
    linkedin: "https://www.linkedin.com/in/badal-raj-400b6b281/",
    description:
      "Leading the Tatva Cell and coordinating its activities. Skilled in event management and team leadership.",
  },
  {
    name: "Pushp Raj",
    designation: "Arthniti Cell Head",
    department: "Student Technical Council - CEP",
    image: AppConfig.imageUrls.arthnitiCellHead,
    email: "pushp_24a11res181@iitp.ac.in",
    linkedin: "https://www.linkedin.com/in/pushp-raj-3b9684242/",
    description:
      "Leading the Arthniti Cell and coordinating its activities. Skilled in financial analysis and team leadership.",
  },
  {
    name: "Ritik Raj",
    designation: "Disha Cell Head",
    department: "Student Technical Council - CEP",
    image: AppConfig.imageUrls.dishaCellHead,
    email: "ritik_2312res838@iitp.ac.in",
    linkedin: "https://www.linkedin.com/in/ritik-raj-a6751b2a6/",
    description:
      "Heading the Training & Placement Cell with a mission to empower students with opportunities and professional readiness.",
  },
];

// ============ DEVELOPERS ============
const developers = [
  {
    name: "Ankit Kumar",
    designation: "WebWiser Member",
    department: "STC Development Team",
    image: AppConfig.imageUrls.tatva.ankit,
    email: "ankit_24a12res103@iitp.ac.in",
    linkedin: "",
    description:
      "Led Frontend development and provided crucial Backend support, ensuring seamless integration and optimal performance across the website.",
  },
  {
    name: "Mandeep Nagar",
    designation: "WebWiser Member",
    department: "STC Development Team",
    image: AppConfig.imageUrls.tatva.mandeep,
    email: "mandeep_25s12res200@iitp.ac.in",
    linkedin: "",
    description:
      "Spearheaded Backend architecture while contributing to frontend components, focusing on creating a robust and scalable web application.",
  },
  {
    name: "Mohit Kumar",
    designation: "WebWiser Coordinator",
    department: "STC Development Team",
    image: AppConfig.imageUrls.tatva.mohit,
    email: "mohit_2312res394@iitp.ac.in",
    linkedin: "",
    description:
      "Provided expert guidance and technical insights throughout the development process, helping shape the website's architecture and features.",
  },
  {
    name: "Abhishek Mohanty",
    designation: "WebWiser Sub-Coordinator",
    department: "STC Development Team",
    image: AppConfig.imageUrls.tatva.abhishek,
    email: "abhishek_2312res891@iitp.ac.in",
    linkedin: "",
    description:
      "Played a key role in development, providing technical direction and implementing critical features that elevated the website's capabilities.",
  },
  {
    name: "Abhijeet Kumar",
    designation: "Codered Sub-Coordinator",
    department: "STC Development Team",
    image: AppConfig.imageUrls.tatva.abhijeetkumar,
    email: "abhijeet_2312res11@iitp.ac.in",
    linkedin: "",
    description:
      "Contributed valuable expertise in web development, offering solutions and optimizations that enhanced the website's functionality and user experience.",
  },
  {
    name: "Vatsal Srivastava",
    designation: "Webwiser Member",
    department: "STC Development Team",
    image: "",
    email: "vatsal_2313res728@iitp.ac.in",
    linkedin: "",
    description:
      "Delivered essential technical contributions and innovative solutions that were instrumental in the successful deployment of key website features.",
  },
];

const domains = {
  // ============ TATVA CLUB ============
  tatva: {
    webwiser: {
      title: "WEBWISER",
      branch: "WEB DEVELOPMENT CLUB",
      whatsappLink: "https://chat.whatsapp.com/En8K9bv7qnb3B9MUq8K87U?mode=wwt",
      cardUrl: AppConfig.imageUrls.WebWiserBox2,
      description:
        "Welcome to WebWiser, the Web Development Club at IIT Patna! 🌐 Whether you're a beginner or an experienced developer, join us to explore the ever-evolving world of web technologies. Learn front-end and back-end development, work on exciting projects, and stay updated with the latest industry trends. Let's build the web of tomorrow, today!",
      message: "Crafting digital experiences, one line of code at a time!",
      team: [
        {
          name: "Mohit",
          position: "Coordinator",
          imgUrl: AppConfig.imageUrls.tatva.mohit,
          email: "mohit_2312res394@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/mohiitp/",
          github: "https://github.com/MOHIT-IITP",
        },
        {
          name: "Abhishek",
          position: "Sub-Coordinator",
          imgUrl: AppConfig.imageUrls.tatva.abhishek,
          email: "abhishek_2312res891@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/abhishekiitp891/",
          github: "https://github.com/Abhishek-IITP",
        },
        {
          name: "Ankit",
          position: "Member",
          imgUrl: AppConfig.imageUrls.tatva.ankit,
          email: "ankit_24a12res102@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/ankitkumar1109/",
          github: "https://github.com/ankit9241",
        },
        {
          name: "Mandeep",
          position: "Member",
          imgUrl: AppConfig.imageUrls.tatva.mandeep,
          email: "mandeep_25s12res200@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/mandeepnagar",
          github: "https://github.com/mandeep140",
        },
        {
          name: "Debojyoti",
          position: "Member",
          imgUrl: AppConfig.imageUrls.tatva.debojyoti,
          email: "ddmpersonalworkspace@gmail.com",
          linkedin:
            "https://www.linkedin.com/in/debojyoti-de-majumder-48052b30b/",
          github: "https://github.com/debojyoti10CC",
        },
        {
          name: "Gaurav",
          position: "Member",
          imgUrl: AppConfig.imageUrls.tatva.gaurav,
          email: "gaurav_ua2504cdh70@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/gaurav-kumar-0b7560382",
          github: "https://github.com/kumargauraviitp/",
        },
      ],
    },

    pixelerate: {
      title: "PIXELERATE",
      branch: "UI/UX AND GRAPHIC DESIGN CLUB",
      whatsappLink: "https://chat.whatsapp.com/BlLPgvkqiGeCzyVYNWvlwy?mode=wwt",
      cardUrl: AppConfig.imageUrls.PixelBox2,
      description:
        "Welcome to Pixelerate, the UI/UX and Graphic Design Club at IIT Patna! 🎨✨ Whether you're a design enthusiast or an experienced designer, join us to explore the world of digital design, user experience, and visual communication. Participate in workshops, design challenges, and real-world projects to enhance your skills and build an impressive portfolio.",
      message:
        "Let's create stunning designs and amazing user experiences together!",
      team: [
        {
          name: "Nikhil Agarwal",
          position: "Advisor",
          imgUrl: AppConfig.imageUrls.tatva.nikhil,
          email: "nikhil_pa2508mch134@iitp.ac.in",
          linkedin: "www.linkedin.com/in/nikhil1901",
          github: "https://github.com/nikhil0712-a",
        },
        {
          name: "Ayesha Rahman",
          position: "Coordinator",
          imgUrl: AppConfig.imageUrls.tatva.ayesha,
          email: "ayesha_2412res169@iitp.ac.in",
          linkedin: "www.linkedin.com/in/ayesha-rahman01",
          github: "https://github.com/ayesha-rahman01",
        },
        {
          name: "Arunesh Kumar",
          position: "Sub-Coordinator",
          imgUrl: AppConfig.imageUrls.tatva.arunesh,
          email: "arunesh_24a12res142@iitp.ac.in",
          linkedin: "www.linkedin.com/in/arunesh-kumar-19n11m06y",
        },
        {
          name: "Astitva Verma",
          position: "Member",
          imgUrl: AppConfig.imageUrls.tatva.astitva,
          email: "astitva_ua2504cdh195@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/astitvaverma/",
          github: "https://github.com/astitvaverma",
        },
        {
          name: "Aditi Dwivedi",
          position: "Member",
          imgUrl: AppConfig.imageUrls.tatva.aditi,
          email: " aditi_ua2503cdh366@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/aditi-5071622b1",
          github: "https://github.com/Aditi11111-IIT",
        },
      ],
    },

    appistry: {
      title: "APPISTRY",
      branch: "APP-DEV CLUB",
      whatsappLink: "https://chat.whatsapp.com/CoOC1aVbOcYHt9JGLRNeNO?mode=wwt",
      cardUrl: AppConfig.imageUrls.AppBox2,
      description:
        "Welcome to Appistry, the App Development Club at IIT Patna! 📱💻 Whether you're a beginner or an experienced developer, join us to build amazing mobile and desktop applications. Learn about the latest technologies, frameworks, and best practices in app development. Work on real-world projects and showcase your skills to the world.",
      message: "Let's build the next generation of amazing apps together!",
      team: [
        {
          name: "Ronak Ranjan",
          position: "Coordinator",
          imgUrl: AppConfig.imageUrls.tatva.ronak,
          email: "ronak_24a12res554@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/ronak-ranjan-3a9a38340",
          github: "https://github.com/ronakranjan",
        },
        {
          name: "Raushan Kumar",
          position: "Sub-Coordinator",
          imgUrl: AppConfig.imageUrls.tatva.raushan,
          email: "raushan_24a12res1049@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/raushan-kumar-365252319/",
          github: "https://github.com/raushankumar-iitp",
        },
        {
          name: "Bhaavya Manan",
          position: "Member",
          imgUrl: AppConfig.imageUrls.tatva.bhaavya,
          email: "bhaavya_ua2504aih65@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/bhaavya-manan-b47911388",
          github: "https://github.com/bhaavyam-b25y",
        },
      ],
    },

    synapse: {
      title: "SYNAPSE",
      branch: "AI/ML CLUB",
      whatsappLink: "https://chat.whatsapp.com/HLobDBgihPtDDuvktFfpOr?mode=wwt",
      cardUrl: AppConfig.imageUrls.SynapseBox2,
      description:
        "Welcome to  The AI ML DL Club! 🧠🚀 Dive into the future of Artificial Intelligence, Machine Learning, and Deep Learning. We're here to unravel cutting-edge technologies, bridging the gap between innovation and imagination. Whether you're a beginner or an expert, join us to explore, learn, and build groundbreaking AI solutions. Access top resources, participate in hands-on projects, and collaborate with passionate peers. Let's shape the future of intelligent systems together! 💡💻",
      message: "Unleash the power of AI, one algorithm at a time!",
      team: [
        {
          name: "Deepak Pareek",
          position: "Advisor",
          imgUrl: AppConfig.imageUrls.tatva.Deepak,
          email: "deepak_pa2503mth104@iitp.ac.in",
          linkedin:
            "https://www.linkedin.com/in/deepak-pareek-ml-datascience-mtech-iitpatna",
          github: "https://github.com/deep-pareek31",
        },
        {
          name: "Ramandeep Singh",
          position: "Coordinator",
          imgUrl: AppConfig.imageUrls.tatva.Ramandeep,
          email: "ramandeep_2312res502@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/ramandeep-singh-503077200",
          github: "https://github.com/Raman-Khiva",
        },
        {
          name: "Md Huzaifa Ansari",
          position: "Sub-Coordinator",
          imgUrl: AppConfig.imageUrls.tatva.Huzaifa,
          email: "md_ua2503cdh177@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/md-huzaifa-ansari-830988148",
          github: "https://github.com/AnsariHuzaif97",
        },
        {
          name: "Priyanshu Garg",
          position: "Member",
          imgUrl: AppConfig.imageUrls.tatva.Priyanshu,
          email: "priyanshu_ua2503aih300@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/priyanshu-garg-088a4a375",
          github: "https://github.com/Priyanshucyb",
        },
        {
          name: "Piyush Raj",
          position: "Member",
          imgUrl: AppConfig.imageUrls.tatva.Piyush,
          email: "piyush_24a12res1003@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/piyush-raj-568b79330",
          github: "",
        },
        {
          name: "Sara Sinha",
          position: "Member",
          imgUrl: AppConfig.imageUrls.tatva.Sara,
          email: "sara_24a12res1207@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/sara-sinha-547a58369",
          github: "https://github.com/sarasinha1207",
        },
        {
          name: "Diksha Sharma",
          position: "Member",
          imgUrl: AppConfig.imageUrls.tatva.dikshaSynapse,
          email: "diksha_ua2504cdh62@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/diksha-sharma-25643a374",
          github: "",
        },
      ],
    },

    code_red: {
      title: "CODE RED",
      branch: "COMPETITIVE PROGRAMMING CLUB",
      whatsappLink: "https://chat.whatsapp.com/LKJkLUlkwz40VsqhAz8qme?mode=wwt",
      cardUrl: AppConfig.imageUrls.CodeRedBox2,
      description:
        "Welcome to Code Red, the Competitive Programming Club at IIT Patna! 💻🔥 Whether you're new to coding or a seasoned coder, join us to sharpen your problem-solving skills and prepare for coding competitions. Participate in regular contests, learn advanced algorithms, and get tips from experienced coders.",
      message: "Code. Compete. Conquer.",
      team: [
        {
          name: "Ratna Singh",
          position: "Advisor",
          imgUrl: AppConfig.imageUrls.tatva.ratna,
          email: "ratna_24a02res12@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/ratna-singh-b56baa15b/",
          github: "",
        },
        {
          name: "Abhijeet Kumar",
          position: "Coordinator",
          imgUrl: AppConfig.imageUrls.tatva.abhijeetkumar,
          email: "abhijeet_2312res11@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/abhijeetiitp/",
          github: "https://github.com/Abhi-Jeeet",
        },
        {
          name: "Sakshi Kumari",
          position: "Sub-Coordinator",
          imgUrl: AppConfig.imageUrls.tatva.SakshiKumari,
          email: "sakshi_2312res563@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/sakshi-kumari-b064a5296/",
          github: "https://github.com/272006Sakshi",
        },
        {
          name: "Ronak Dokania",
          position: "Member",
          imgUrl: AppConfig.imageUrls.tatva.RonakDokania,
          email: "ronak_25s12res140@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/ronak-dokania-40a34328b/",
          github: "https://github.com/RonakDokania",
        },
        {
          name: "Vipul Krishna Pandey",
          position: "Member",
          imgUrl: AppConfig.imageUrls.tatva.vipul,
          email: "vipul_us2603cdh73@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/vipul-krishna-1251062b0",
          github: "https://github.com/Roxen1449",
        },
      ],
    },

    analytical_arena: {
      title: "ANALYTICAL ARENA",
      branch: "DATA SCIENCE CLUB",
      whatsappLink: "https://chat.whatsapp.com/ChIMsbcwzqYLg9tTJyFuZp?mode=wwt",
      cardUrl: AppConfig.imageUrls.ArenaBox2,
      description:
        "Welcome to Analytical Arena, the Data Science & Analytics Club at IIT Patna! 📊🔍 Whether you're just starting out or a data wizard, this is your go-to group. Immerse yourself in the fascinating world of data analytics, machine learning, and big data. Join us to access valuable resources, engage in insightful discussions, and participate in challenging projects.",
      message: "Transforming data into insights, one algorithm at a time!",
      team: [
        {
          name: "Reshma Selvaraj",
          position: "Advisor",
          imgUrl: AppConfig.imageUrls.tatva.reshma,
          email: "reshma_pa2511aih31@iitp.ac.in",
          linkedin: "http://linkedin.com/in/reshma-selvaraj-129764191",
          github: "https://github.com/Reshmaselvaraj",
        },
        {
          name: "Suyash Mukherjee",
          position: "Coordinator",
          imgUrl: AppConfig.imageUrls.tatva.suyash,
          email: "suyash_2312res690@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/suyashmukherjee/",
          github: "https://github.com/suyash1912",
        },
        {
          name: "Aastha Anand",
          position: "Sub-Coordinator",
          imgUrl: AppConfig.imageUrls.tatva.aastha,
          email: "aastha_2312res753@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/aastha-anand-7138b4368/",
          github: "https://github.com/aastha-byte",
        },
        {
          name: "Diksha Ballav",
          position: "Member",
          imgUrl: AppConfig.imageUrls.tatva.diksha,
          email: "diksha_2412res171@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/diksha-ballav-a79049312/",
          github: "https://github.com/DikshaBallav",
        },
        {
          name: "Tripti Rani Kachhap",
          position: "Member",
          imgUrl: AppConfig.imageUrls.tatva.tripti,
          email: "tripti_25s12res179@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/tripti-rani-kachhap-aa558b340",
          github: "https://github.com/dystopiandust",
        },
      ],
    },

    hackshield: {
      title: "HACKSHIELD",
      branch: "CYBERSECURITY CLUB",
      whatsappLink: "https://chat.whatsapp.com/Kk4EPaNeHkp8oNQZ8O0ZR7?mode=wwt",
      cardUrl: AppConfig.imageUrls.HackBox2,
      description:
        "Welcome to HackShield, the Cybersecurity Club at IIT Patna! 🔒💻 Whether you're a security enthusiast or looking to start your journey in cybersecurity, join us to learn about ethical hacking, network security, and digital forensics. Participate in CTF challenges, workshops, and security research to enhance your skills.",
      message: "Securing the digital world, one byte at a time!",
      team: [
        // {
        //   name: "Aditya Tomar",
        //   position: "Sub-Coordinator",
        //   imgUrl: AppConfig.imageUrls.tatva.adityaHackShield,
        //   email: "aditya_ua2503aih19@iitp.ac.in",
        //   linkedin: "https://linkedin.com/in/brsrk94",
        //   github: "https://github.com/brsrk94",
        // },
        {
          name: "Ripunjay",
          position: "Member",
          imgUrl: AppConfig.imageUrls.tatva.ripunjay,
          email: "ripunjay_ua2504aih176@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/ripunjay-mishra-455316377",
          github: "",
        },
        {
          name: "Suman",
          position: "Member",
          imgUrl: AppConfig.imageUrls.tatva.suman,
          email: "suman_2312res675@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/sumankumar-/",
          github: "",
        },
        // {
        //   name: "Yash Bhopale",
        //   position: "Member",
        //   imgUrl: AppConfig.imageUrls.tatva.yash,
        //   email: "Yash_ua2504aih274@iitp.ac.in",
        //   linkedin: "https://www.linkedin.com/in/yashbhople/",
        //   github: "",
        // },
      ],
    },

    tech_hub: {
      title: "TECH HUB",
      branch: "TECHNICAL CLUB",
      whatsappLink: "https://chat.whatsapp.com/InjNSSAY1REKYgeAKOkF6u?mode=wwt",
      cardUrl: AppConfig.imageUrls.TechHubBox2,
      description:
        "Welcome to Tech Hub, the central hub for all things tech at IIT Patna! 🚀 Whether you're interested in learning new technologies, working on innovative projects, or attending insightful sessions, Tech Hub is the place to be. Join us to expand your knowledge, collaborate with peers, and stay ahead in the fast-paced world of technology.",
      message: "Empowering innovation through technology and collaboration!",
      team: [
        {
          name: "Manas Mishra",
          position: "Advisor",
          imgUrl: AppConfig.imageUrls.tatva.manas,
          email: "manas_pa2503mth193@iitp.ac.in",
          linkedin: "https://in.linkedin.com/in/manas--mishra",
          github: "https://github.com/manas-sde",
        },
        {
          name: "Amarjeet Kumar",
          position: "Coordinator",
          imgUrl: AppConfig.imageUrls.tatva.amarjeet,
          email: "amarjeet_24a12res78@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/amarjeet-kumar-628451323",
          github: "https://github.com/MADxTYRANT",
        },
        {
          name: "Shreya Anand",
          position: "Sub-Coordinator",
          imgUrl: AppConfig.imageUrls.tatva.shreya,
          email: "shreya_2312res860@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/shreya-anand1803/",
          github: "https://github.com/ShreyaAnand1810",
        },
        {
          name: "Ambikesh Singh",
          position: "Member",
          imgUrl: AppConfig.imageUrls.tatva.ambikesh,
          email: "ambikesh_ua2504aih289@iitp.ac.in",
          linkedin: "https://in.linkedin.com/in/ambikesh-singh-6814603b8",
          github: "https://github.com/Ambikesh-Singh",
        },
        {
          name: "Divya Prakash",
          position: "Member",
          imgUrl: AppConfig.imageUrls.tatva.divya,
          email: "divya_ua2503cdh632@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/divya-prakash-1127203a1",
          github: "https://github.com/omprakashpatna18-del",
        },
      ],
    },

    mech_x: {
      title: "MECH-X",
      branch: "ROBOTICS CLUB",
      whatsappLink: "https://chat.whatsapp.com/Lvf6wrSHYTr4sDeuWBWTM0?mode=wwt",
      cardUrl: AppConfig.imageUrls.MechXBox2,
      description:
        "Welcome to Mech-X, the Robotics Club at IIT Patna! 🔧⚙️ Whether you're passionate about robotics, automotive engineering, or mechanical design, Mech-X is your platform to explore and innovate. Join us for hands-on workshops, competitions, and projects that will help you apply theoretical knowledge to real-world mechanical engineering challenges.",
      message: "Robotics is the future, one mechanism at a time!",
      team: [
        {
          name: "Nidhi Chandrakar",
          position: "Advisor",
          imgUrl: AppConfig.imageUrls.tatva.nidhi,
          email: "nidhi_ps2611aih45@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/nidhichandrakar25",
          github: "https://github.com/nidhichandrakar",
        },
        {
          name: "Vishnu Kumar Dhoni",
          position: "Coordinator",
          imgUrl: AppConfig.imageUrls.tatva.VishnuMechX,
          email: "vishnu_24a12res771@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/vishnu-kumar-5b94502a0/",
          github: "https://github.com/vishnu-iitp",
        },
        {
          name: "Abhishek Kumar",
          position: "Sub-Coordinator",
          imgUrl: AppConfig.imageUrls.tatva.abhishekMechX,
          email: "abhishek_2412res06@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/abhishek-050577268/",
          github: "https://github.com/techx-aether",
        },
        {
          name: "Adarsh Raj",
          position: "Member",
          imgUrl: AppConfig.imageUrls.tatva.adarsh,
          email: "adarsh_ua2503aih10@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/adarsh-raj-bb0510364",
          github: "https://github.com/Adarsh-repo11",
        },
        {
          name: "Vipul Krishna Pandey",
          position: "Member",
          imgUrl: AppConfig.imageUrls.tatva.vipulMechX,
          email: "vipul_us2603cdh73@iitp.ac.in",
          linkedin: "https://www.linkedin.com/in/vipul-krishna-1251062b0/",
          github: "https://github.com/Roxen1449",
        },
        {
          name: "Aditya Raj",
          position: "Member",
          imgUrl: AppConfig.imageUrls.tatva.adityaMechX,
          email: "aditya_24a12res817@iitp.ac.in",
          linkedin: "https://linkedin.com/in/aditya-raj-354686334",
          github: "https://github.com/aditya-raj009",
        },
      ],
    },
  },

  // ============ DISHA CLUB ============
  disha: {
      careerCatalyst: {
        title: "CAREER CATALYST",
        branch: "CAREER DEVELOPMENT CLUB",
        whatsappLink: "https://chat.whatsapp.com/example",
        cardUrl: AppConfig.imageUrls.ArenaBox2,
        description:
          "Welcome to Career Catalyst, the Career Development Club! 🚀 Whether you're exploring career options or preparing for placements, join us to build your professional skills and network with industry experts.",
        message: "Catalyzing careers, one opportunity at a time!",
        team: [
          {
            name: "Mahak",
            position: "Coordinator",
            imgUrl: AppConfig.imageUrls.disha.mahak,
            email: "mahak@iitp.ac.in",
            linkedin: "https://linkedin.com/in/mahak",
            github: "",
          },
          {
            name: "Prakash",
            position: "Member",
            imgUrl: AppConfig.imageUrls.disha.prakash,
            email: "prakash@iitp.ac.in",
            linkedin: "https://linkedin.com/in/prakash",
            github: "",
          },
          {
            name: "Shaurya",
            position: "Member",
            imgUrl: AppConfig.imageUrls.disha.shaurya,
            email: "shaurya@iitp.ac.in",
            linkedin: "https://linkedin.com/in/shaurya",
            github: "",
          },
          {
            name: "Vikash",
            position: "Member",
            imgUrl: AppConfig.imageUrls.disha.vikash,
            email: "vikash@iitp.ac.in",
            linkedin: "https://linkedin.com/in/vikash",
            github: "",
          },
        ],
      },
      opportune: {
        title: "OPPORTUNE",
        branch: "OPPORTUNITY CLUB",
        whatsappLink: "https://chat.whatsapp.com/example",
        cardUrl: AppConfig.imageUrls.CodeRedBox2,
        description:
          "Welcome to Opportune, the Opportunity Club! 💼 Whether you're seeking internships, projects, or career opportunities, join us to connect with the right opportunities at the right time.",
        message: "Creating opportunities, one connection at a time!",
        team: [
          {
            name: "Abhishek",
            position: "Advisor",
            imgUrl: AppConfig.imageUrls.disha.abhishekAdvisor,
            email: "abhishek@iitp.ac.in",
            linkedin: "https://linkedin.com/in/abhishek",
            github: "",
          },
          {
            name: "Ahtisham",
            position: "Coordinator",
            imgUrl: AppConfig.imageUrls.disha.ahtisham,
            email: "ahtisham@iitp.ac.in",
            linkedin: "https://linkedin.com/in/ahtisham",
            github: "",
          },
          {
            name: "Ankit",
            position: "Sub-Coordinator",
            imgUrl: AppConfig.imageUrls.disha.ankitDisha,
            email: "ankit@iitp.ac.in",
            linkedin: "https://linkedin.com/in/ankit",
            github: "",
          },
          {
            name: "Abhinav",
            position: "Member",
            imgUrl: AppConfig.imageUrls.disha.abhinav,
            email: "abhinav@iitp.ac.in",
            linkedin: "https://linkedin.com/in/abhinav",
            github: "",
          },
          {
            name: "Amit",
            position: "Member",
            imgUrl: AppConfig.imageUrls.disha.amit,
            email: "amit@iitp.ac.in",
            linkedin: "https://linkedin.com/in/amit",
            github: "",
          },
          {
            name: "Arpit",
            position: "Member",
            imgUrl: AppConfig.imageUrls.disha.arpit,
            email: "arpit@iitp.ac.in",
            linkedin: "https://linkedin.com/in/arpit",
            github: "",
          },
          {
            name: "Raj",
            position: "Member",
            imgUrl: AppConfig.imageUrls.disha.raj,
            email: "raj@iitp.ac.in",
            linkedin: "https://linkedin.com/in/raj",
            github: "",
          },
        ],
      },
  },

  // ============ ARTHNITI CLUB ============
  arthniti: {
      foundersForge: {
        title: "FOUNDERS FORGE",
        branch: "ENTREPRENEURSHIP CLUB",
        whatsappLink: "https://chat.whatsapp.com/example",
        cardUrl: AppConfig.imageUrls.SynapseBox2,
        description:
          "Welcome to Founders Forge, the Entrepreneurship Club! 🚀 Whether you have a startup idea or want to join a founding team, this is your platform to turn ideas into reality.",
        message: "Forging founders, one startup at a time!",
        team: [
          {
            name: "Apramayo",
            position: "Coordinator",
            imgUrl: AppConfig.imageUrls.arthniti.apramayo,
            email: "apramayo@iitp.ac.in",
            linkedin: "https://linkedin.com/in/apramayo",
            github: "",
          },
          {
            name: "Dennis",
            position: "Member",
            imgUrl: AppConfig.imageUrls.arthniti.dennis,
            email: "dennis@iitp.ac.in",
            linkedin: "https://linkedin.com/in/dennis",
            github: "",
          },
          {
            name: "Faridjot",
            position: "Member",
            imgUrl: AppConfig.imageUrls.arthniti.faridjot,
            email: "faridjot@iitp.ac.in",
            linkedin: "https://linkedin.com/in/faridjot",
            github: "",
          },
          {
            name: "Ramesh",
            position: "Member",
            imgUrl: AppConfig.imageUrls.arthniti.ramesh,
            email: "ramesh@iitp.ac.in",
            linkedin: "https://linkedin.com/in/ramesh",
            github: "",
          },
          {
            name: "Shiv",
            position: "Member",
            imgUrl: AppConfig.imageUrls.arthniti.shivFounders,
            email: "shiv@iitp.ac.in",
            linkedin: "https://linkedin.com/in/shiv",
            github: "",
          },
          {
            name: "Yuvraj",
            position: "Member",
            imgUrl: AppConfig.imageUrls.arthniti.yuvraj,
            email: "yuvraj@iitp.ac.in",
            linkedin: "https://linkedin.com/in/yuvraj",
            github: "",
          },
        ],
      },
      freelanthropy: {
        title: "FREELANTHROPY",
        branch: "FREELANCING CLUB",
        whatsappLink: "https://chat.whatsapp.com/example",
        cardUrl: AppConfig.imageUrls.PixelBox2,
        description:
          "Welcome to Freelanthropy, the Freelancing Club! 💼 Whether you want to start freelancing or grow your freelance business, join us to learn the art of independent work.",
        message: "Empowering freelancers, one project at a time!",
        team: [
          {
            name: "Debabrata",
            position: "Coordinator",
            imgUrl: AppConfig.imageUrls.arthniti.debabrata,
            email: "debabrata@iitp.ac.in",
            linkedin: "https://linkedin.com/in/debabrata",
            github: "",
          },
          {
            name: "Raunak",
            position: "Member",
            imgUrl: AppConfig.imageUrls.arthniti.raunakArthniti,
            email: "raunak@iitp.ac.in",
            linkedin: "https://linkedin.com/in/raunak",
            github: "",
          },
          {
            name: "Shivam",
            position: "Member",
            imgUrl: AppConfig.imageUrls.arthniti.shivam,
            email: "shivam@iitp.ac.in",
            linkedin: "https://linkedin.com/in/shivam",
            github: "",
          },
        ],
      },
  },

  // ============ MANAGEMENT CLUB ============
  management: {
      creative: {
        title: "CREATIVE",
        branch: "CREATIVE CLUB",
        whatsappLink: "https://chat.whatsapp.com/example",
        cardUrl: AppConfig.imageUrls.AppBox2,
        description:
          "Welcome to Creative, the Creative Club! 🎨 Whether you're into design, content creation, or creative arts, join us to express your creativity and collaborate on amazing projects.",
        message: "Creating creativity, one masterpiece at a time!",
        team: [
          {
            name: "Anshika",
            position: "Coordinator",
            imgUrl: AppConfig.imageUrls.management.anshika,
            email: "anshika@iitp.ac.in",
            linkedin: "https://linkedin.com/in/anshika",
            github: "",
          },
          {
            name: "Aparna",
            position: "Member",
            imgUrl: AppConfig.imageUrls.management.aparna,
            email: "aparna@iitp.ac.in",
            linkedin: "https://linkedin.com/in/aparna",
            github: "",
          },
          {
            name: "Shambhavi",
            position: "Member",
            imgUrl: AppConfig.imageUrls.management.shambhavi,
            email: "shambhavi@iitp.ac.in",
            linkedin: "https://linkedin.com/in/shambhavi",
            github: "",
          },
          {
            name: "Vinayak",
            position: "Member",
            imgUrl: AppConfig.imageUrls.management.vinayak,
            email: "vinayak@iitp.ac.in",
            linkedin: "https://linkedin.com/in/vinayak",
            github: "",
          },
          {
            name: "Amarjeet",
            position: "Member",
            imgUrl: AppConfig.imageUrls.management.amarjeetCreative,
            email: "amarjeet@iitp.ac.in",
            linkedin: "https://linkedin.com/in/amarjeet",
            github: "",
          },
          {
            name: "Shruti",
            position: "Member",
            imgUrl: AppConfig.imageUrls.management.shruti,
            email: "shruti@iitp.ac.in",
            linkedin: "https://linkedin.com/in/shruti",
            github: "",
          },
          {
            name: "Yash",
            position: "Member",
            imgUrl: AppConfig.imageUrls.management.yashCreative,
            email: "yash@iitp.ac.in",
            linkedin: "https://linkedin.com/in/yash",
            github: "",
          },
        ],
      },
      eventManagement: {
        title: "EVENT MANAGEMENT",
        branch: "EVENT MANAGEMENT CLUB",
        whatsappLink: "https://chat.whatsapp.com/example",
        cardUrl: AppConfig.imageUrls.HackBox2,
        description:
          "Welcome to Event Management, the Event Management Club! 🎪 Whether you love organizing events or managing logistics, join us to create memorable experiences and develop your event management skills.",
        message: "Managing events, one experience at a time!",
        team: [
          {
            name: "Alquama",
            position: "Coordinator",
            imgUrl: AppConfig.imageUrls.management.alquama,
            email: "alquama@iitp.ac.in",
            linkedin: "https://linkedin.com/in/alquama",
            github: "",
          },
          {
            name: "Harshit",
            position: "Member",
            imgUrl: AppConfig.imageUrls.management.harshit,
            email: "harshit@iitp.ac.in",
            linkedin: "https://linkedin.com/in/harshit",
            github: "",
          },
          {
            name: "Isha",
            position: "Member",
            imgUrl: AppConfig.imageUrls.management.ishaEvent,
            email: "isha@iitp.ac.in",
            linkedin: "https://linkedin.com/in/isha",
            github: "",
          },
          {
            name: "Prince",
            position: "Member",
            imgUrl: AppConfig.imageUrls.management.prince,
            email: "prince@iitp.ac.in",
            linkedin: "https://linkedin.com/in/prince",
            github: "",
          },
          {
            name: "Sambhaw",
            position: "Member",
            imgUrl: AppConfig.imageUrls.management.sambhaw,
            email: "sambhaw@iitp.ac.in",
            linkedin: "https://linkedin.com/in/sambhaw",
            github: "",
          },
          {
            name: "Sachin",
            position: "Member",
            imgUrl: AppConfig.imageUrls.management.sachin,
            email: "sachin@iitp.ac.in",
            linkedin: "https://linkedin.com/in/sachin",
            github: "",
          },
        ],
      },
      pr: {
        title: "PR",
        branch: "PUBLIC RELATIONS CLUB",
        whatsappLink: "https://chat.whatsapp.com/example",
        cardUrl: AppConfig.imageUrls.TechHubBox2,
        description:
          "Welcome to PR, the Public Relations Club! 📢 Whether you're into communications, branding, or public speaking, join us to build your PR skills and represent the organization.",
        message: "Building relationships, one connection at a time!",
        team: [
          {
            name: "Ananya",
            position: "Coordinator",
            imgUrl: AppConfig.imageUrls.management.ananya,
            email: "ananya@iitp.ac.in",
            linkedin: "https://linkedin.com/in/ananya",
            github: "",
          },
          {
            name: "Aryan",
            position: "Member",
            imgUrl: AppConfig.imageUrls.management.aryanPR,
            email: "aryan@iitp.ac.in",
            linkedin: "https://linkedin.com/in/aryan",
            github: "",
          },
          {
            name: "Harsh",
            position: "Member",
            imgUrl: AppConfig.imageUrls.management.harsh,
            email: "harsh@iitp.ac.in",
            linkedin: "https://linkedin.com/in/harsh",
            github: "",
          },
          {
            name: "Soni",
            position: "Member",
            imgUrl: AppConfig.imageUrls.management.soni,
            email: "soni@iitp.ac.in",
            linkedin: "https://linkedin.com/in/soni",
            github: "",
          },
          {
            name: "Sumit",
            position: "Member",
            imgUrl: AppConfig.imageUrls.management.sumit,
            email: "sumit@iitp.ac.in",
            linkedin: "https://linkedin.com/in/sumit",
            github: "",
          },
          {
            name: "Tanu",
            position: "Member",
            imgUrl: AppConfig.imageUrls.management.tanu,
            email: "tanu@iitp.ac.in",
            linkedin: "https://linkedin.com/in/tanu",
            github: "",
          },
        ],
      },
      sessionWebinar: {
        title: "SESSION & WEBINAR",
        branch: "SESSION & WEBINAR CLUB",
        whatsappLink: "https://chat.whatsapp.com/example",
        cardUrl: AppConfig.imageUrls.MechXBox2,
        description:
          "Welcome to Session & Webinar, the Session & Webinar Club! 🎥 Whether you love organizing sessions, webinars, or workshops, join us to bring knowledge and expertise to the community.",
        message: "Sharing knowledge, one session at a time!",
        team: [
          {
            name: "Honey",
            position: "Coordinator",
            imgUrl: AppConfig.imageUrls.management.honey,
            email: "honey@iitp.ac.in",
            linkedin: "https://linkedin.com/in/honey",
            github: "",
          },
          {
            name: "Jayati",
            position: "Member",
            imgUrl: AppConfig.imageUrls.management.jayati,
            email: "jayati@iitp.ac.in",
            linkedin: "https://linkedin.com/in/jayati",
            github: "",
          },
          {
            name: "Isha",
            position: "Member",
            imgUrl: AppConfig.imageUrls.management.ishaSession,
            email: "isha@iitp.ac.in",
            linkedin: "https://linkedin.com/in/isha",
            github: "",
          },
          {
            name: "Shobhit",
            position: "Member",
            imgUrl: AppConfig.imageUrls.management.Shobhit,
            email: "shobhit@iitp.ac.in",
            linkedin: "#",
            github: "",
          },
        ],
      },
      sponsor: {
        title: "SPONSOR",
        branch: "SPONSORSHIP CLUB",
        whatsappLink: "https://chat.whatsapp.com/example",
        cardUrl: AppConfig.imageUrls.SessionBox2,
        description:
          "Welcome to Sponsor, the Sponsorship Club! 💰 Whether you're into fundraising, sponsor relations, or partnership building, join us to secure resources for our initiatives.",
        message: "Securing partnerships, one sponsor at a time!",
        team: [
          {
            name: "Anmol",
            position: "Coordinator",
            imgUrl: AppConfig.imageUrls.management.anmol,
            email: "anmol@iitp.ac.in",
            linkedin: "https://linkedin.com/in/anmol",
            github: "",
          },
          {
            name: "Pragati",
            position: "Member",
            imgUrl: AppConfig.imageUrls.management.pragati,
            email: "pragati@iitp.ac.in",
            linkedin: "https://linkedin.com/in/pragati",
            github: "",
          },
          {
            name: "Pratishtha",
            position: "Member",
            imgUrl: AppConfig.imageUrls.management.pratishtha,
            email: "pratishtha@iitp.ac.in",
            linkedin: "https://linkedin.com/in/pratishtha",
            github: "",
          },
          {
            name: "Shourya",
            position: "Member",
            imgUrl: AppConfig.imageUrls.management.shourya,
            email: "shourya@iitp.ac.in",
            linkedin: "https://linkedin.com/in/shourya",
            github: "",
          },
        ],
      },
  },
};
// Export all team data for use in components
export { coreTeam, councilMembers, developers };
export default domains;
